// Bridges the schedule generator to concrete `StudySession` records so the
// dashboard/calendar can render auto-planned work alongside manual tasks.
// Recomputed whenever subjects/assignments/exams/availability change.

import type { Assignment, Exam, StudySession, Subject } from '../types';
import { generateSchedule } from './scheduleGenerator';

type DraftSession = Omit<StudySession, 'id'>;

function remainingTopicNames(subject: Subject | undefined): string[] {
  if (!subject) return [];
  return subject.topics.filter((t) => !t.covered).map((t) => t.name);
}

export function buildAutoSessions(subjects: Subject[], assignments: Assignment[], exams: Exam[]): DraftSession[] {
  const subjectMap = new Map(subjects.map((s) => [s.id, s]));
  const sessions: DraftSession[] = [];

  for (const exam of exams) {
    const subject = subjectMap.get(exam.subjectId);
    const topics = remainingTopicNames(subject);
    const plan = generateSchedule(topics, exam.date, exam.difficulty, exam.preparedness);
    for (const day of plan) {
      sessions.push({
        subjectId: exam.subjectId,
        title: day.isReviewDay
          ? `Review for ${subject?.name ?? 'Exam'}`
          : `Study: ${day.topics.join(', ')}`,
        date: day.date,
        durationMins: Math.round(day.estimatedHours * 60),
        completed: false,
        autoGenerated: true,
        sourceId: exam.id,
      });
    }
  }

  for (const assignment of assignments) {
    if (assignment.status === 'submitted') continue;
    const subject = subjectMap.get(assignment.subjectId);
    const topics = remainingTopicNames(subject);
    const plan = generateSchedule(topics, assignment.deadline, subject?.difficulty ?? 'med', subject?.progress ?? 0);
    for (const day of plan) {
      sessions.push({
        subjectId: assignment.subjectId,
        title: day.isReviewDay
          ? `Wrap up: ${assignment.title}`
          : `Work on ${assignment.title}: ${day.topics.join(', ')}`,
        date: day.date,
        durationMins: Math.round(day.estimatedHours * 60),
        completed: false,
        autoGenerated: true,
        sourceId: assignment.id,
      });
    }
  }

  return sessions;
}

// Preserve completion state (and identity) of existing auto-generated
// sessions that match a freshly generated one on (sourceId, date), so ticking
// off a planned session doesn't get wiped out by the next recompute.
export function mergeAutoSessions(existing: StudySession[], fresh: DraftSession[]): DraftSession[] {
  const existingBySourceDate = new Map(existing.map((s) => [`${s.sourceId}|${s.date}`, s]));
  return fresh.map((draft) => {
    const key = `${draft.sourceId}|${draft.date}`;
    const match = existingBySourceDate.get(key);
    return match ? { ...draft, completed: match.completed } : draft;
  });
}
