// Core domain types for StudyNova. Kept framework-agnostic so the data
// access layer and UI can both depend on a single source of truth.

export type Difficulty = 'low' | 'med' | 'high';

export interface Topic {
  name: string;
  covered: boolean;
}

export interface Subject {
  id: string;
  name: string;
  difficulty: Difficulty;
  progress: number; // 0-100, derived from topics but stored for quick access
  topics: Topic[];
  color?: string; // for charts/calendar chips
  createdAt: string; // ISO date
}

export type AssignmentStatus = 'not-started' | 'in-progress' | 'submitted';

export interface Assignment {
  id: string;
  subjectId: string;
  title: string;
  deadline: string; // ISO date
  weight: number; // importance, 1-10
  status: AssignmentStatus;
  createdAt: string;
}

export interface Exam {
  id: string;
  subjectId: string;
  date: string; // ISO date
  difficulty: Difficulty;
  preparedness: number; // 0-100
  practiceTestsDone: number;
  createdAt: string;
}

export interface StudySession {
  id: string;
  subjectId: string;
  title: string;
  date: string; // ISO date (day the session is scheduled)
  durationMins: number;
  completed: boolean;
  // Set when this session was produced by the schedule generator so it can
  // be regenerated/replaced without touching manually created sessions.
  autoGenerated?: boolean;
  sourceId?: string; // id of the Exam/Assignment this session targets
}

export type FocusSessionType = '25' | '50';

export interface FocusSession {
  id: string;
  date: string; // ISO date
  type: FocusSessionType;
  durationMins: number;
  completed: boolean;
}

export interface TimeBlock {
  start: string; // "HH:MM"
  end: string; // "HH:MM"
}

export interface DailyAvailability {
  dayOfWeek: number; // 0 = Sunday .. 6 = Saturday
  freeTimeBlocks: TimeBlock[];
}

export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string; // emoji for simplicity
  unlockedAt: string | null; // ISO date, null = locked
}

export interface XPState {
  totalXP: number;
  level: number;
  badges: Badge[];
}

export interface AppNotification {
  id: string;
  title: string;
  body: string;
  createdAt: string;
  read: boolean;
  kind: 'exam' | 'deadline' | 'session' | 'achievement' | 'info';
  dedupeKey: string; // prevents the same reminder firing repeatedly
}

// Root shape persisted by the data-access layer.
export interface StudyNovaData {
  subjects: Subject[];
  assignments: Assignment[];
  exams: Exam[];
  studySessions: StudySession[];
  focusSessions: FocusSession[];
  availability: DailyAvailability[];
  xp: XPState;
  notifications: AppNotification[];
}
