import type {
  Assignment,
  DailyAvailability,
  Exam,
  FocusSession,
  StudyNovaData,
  StudySession,
  Subject,
  AppNotification,
  XPState,
} from '../types';
import type { DataStore } from './storage';
import { LocalStorageStore } from './storage';
import { buildSeedData } from './seed';

const STORAGE_KEY = 'studynova:data:v1';

export function newId(prefix: string): string {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

// Repository is the single entry point every component/context uses to read
// and write app data. It owns the in-memory copy, persists on every mutation,
// and is the only class aware of `StudyNovaData`'s shape + the storage
// adapter underneath it. Swapping localStorage for a real backend later only
// requires changing the `store` implementation passed into the constructor.
export class Repository {
  private store: DataStore;
  private data: StudyNovaData | null = null;

  constructor(store: DataStore = new LocalStorageStore()) {
    this.store = store;
  }

  async load(): Promise<StudyNovaData> {
    if (this.data) return this.data;
    const existing = await this.store.load<StudyNovaData>(STORAGE_KEY);
    this.data = existing ?? buildSeedData();
    if (!existing) await this.persist();
    return this.data;
  }

  getSnapshot(): StudyNovaData {
    if (!this.data) throw new Error('Repository.load() must be called before use');
    return this.data;
  }

  private async persist(): Promise<void> {
    if (!this.data) return;
    await this.store.save(STORAGE_KEY, this.data);
  }

  private async mutate(fn: (data: StudyNovaData) => void): Promise<StudyNovaData> {
    const data = this.getSnapshot();
    fn(data);
    await this.persist();
    return data;
  }

  // ---- Subjects ----
  addSubject(input: Omit<Subject, 'id' | 'createdAt'>) {
    return this.mutate((data) => {
      data.subjects.push({ ...input, id: newId('subj'), createdAt: new Date().toISOString() });
    });
  }
  updateSubject(id: string, patch: Partial<Subject>) {
    return this.mutate((data) => {
      const s = data.subjects.find((x) => x.id === id);
      if (s) Object.assign(s, patch);
    });
  }
  deleteSubject(id: string) {
    return this.mutate((data) => {
      data.subjects = data.subjects.filter((x) => x.id !== id);
      data.assignments = data.assignments.filter((x) => x.subjectId !== id);
      data.exams = data.exams.filter((x) => x.subjectId !== id);
      data.studySessions = data.studySessions.filter((x) => x.subjectId !== id);
    });
  }

  // ---- Assignments ----
  addAssignment(input: Omit<Assignment, 'id' | 'createdAt'>) {
    return this.mutate((data) => {
      data.assignments.push({ ...input, id: newId('asg'), createdAt: new Date().toISOString() });
    });
  }
  updateAssignment(id: string, patch: Partial<Assignment>) {
    return this.mutate((data) => {
      const a = data.assignments.find((x) => x.id === id);
      if (a) Object.assign(a, patch);
    });
  }
  deleteAssignment(id: string) {
    return this.mutate((data) => {
      data.assignments = data.assignments.filter((x) => x.id !== id);
    });
  }

  // ---- Exams ----
  addExam(input: Omit<Exam, 'id' | 'createdAt'>) {
    return this.mutate((data) => {
      data.exams.push({ ...input, id: newId('exam'), createdAt: new Date().toISOString() });
    });
  }
  updateExam(id: string, patch: Partial<Exam>) {
    return this.mutate((data) => {
      const e = data.exams.find((x) => x.id === id);
      if (e) Object.assign(e, patch);
    });
  }
  deleteExam(id: string) {
    return this.mutate((data) => {
      data.exams = data.exams.filter((x) => x.id !== id);
    });
  }

  // ---- Study Sessions ----
  addStudySession(input: Omit<StudySession, 'id'>) {
    return this.mutate((data) => {
      data.studySessions.push({ ...input, id: newId('sess') });
    });
  }
  updateStudySession(id: string, patch: Partial<StudySession>) {
    return this.mutate((data) => {
      const s = data.studySessions.find((x) => x.id === id);
      if (s) Object.assign(s, patch);
    });
  }
  deleteStudySession(id: string) {
    return this.mutate((data) => {
      data.studySessions = data.studySessions.filter((x) => x.id !== id);
    });
  }
  // Replace all auto-generated sessions with a freshly computed plan while
  // leaving manually created sessions untouched.
  replaceAutoGeneratedSessions(sessions: Omit<StudySession, 'id'>[]) {
    return this.mutate((data) => {
      data.studySessions = data.studySessions.filter((x) => !x.autoGenerated);
      data.studySessions.push(...sessions.map((s) => ({ ...s, id: newId('sess') })));
    });
  }

  // ---- Focus Sessions ----
  addFocusSession(input: Omit<FocusSession, 'id'>) {
    return this.mutate((data) => {
      data.focusSessions.push({ ...input, id: newId('focus') });
    });
  }

  // ---- Availability ----
  setAvailability(availability: DailyAvailability[]) {
    return this.mutate((data) => {
      data.availability = availability;
    });
  }

  // ---- XP ----
  setXP(xp: XPState) {
    return this.mutate((data) => {
      data.xp = xp;
    });
  }

  // ---- Notifications ----
  addNotification(input: Omit<AppNotification, 'id' | 'createdAt' | 'read'>) {
    return this.mutate((data) => {
      data.notifications.unshift({
        ...input,
        id: newId('notif'),
        createdAt: new Date().toISOString(),
        read: false,
      });
    });
  }
  markNotificationRead(id: string) {
    return this.mutate((data) => {
      const n = data.notifications.find((x) => x.id === id);
      if (n) n.read = true;
    });
  }
  markAllNotificationsRead() {
    return this.mutate((data) => {
      data.notifications.forEach((n) => (n.read = true));
    });
  }
}

export const repository = new Repository();
